[package]
name = "databas"
version = '0.1.0'
authors = ['writemorecode']
edition = '2024'
repository = 'https://github.com/writemorecode/databas'

[dependencies]
crc = "3.4.0"
thiserror = "2.0.18"

[dev-dependencies]
fastrand = "2.3.0"
proptest = "1.9.0"
tempfile = "3.25.0"

[lints.clippy]
# Don't panic
expect_used = "deny"
get_unwrap = "deny"
panic = "deny"
panic_in_result_fn = "deny"
todo = "deny"
unchecked_time_subtraction = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"

cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_sign_loss = "deny"

map_err_ignore = "deny"
